<?php

declare(strict_types=1);

namespace Flux\OdooApiClient\Model\Object\Stock\Warehouse;

use DateTimeInterface;
use Flux\OdooApiClient\Model\Object\Base;
use Flux\OdooApiClient\Model\OdooRelation;
use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * Odoo model : stock.warehouse.orderpoint
 * ---
 * Name : stock.warehouse.orderpoint
 * ---
 * Info :
 * Defines Minimum stock rules.
 */
final class Orderpoint extends Base
{
    /**
     * Name
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var string
     */
    private $name;

    /**
     * Trigger
     * ---
     * Selection :
     *     -> auto (Auto)
     *     -> manual (Manual)
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var string
     */
    private $trigger;

    /**
     * Active
     * ---
     * If the active field is set to False, it will allow you to hide the orderpoint without removing it.
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var bool|null
     */
    private $active;

    /**
     * Snoozed
     * ---
     * Hidden until next scheduler.
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var DateTimeInterface|null
     */
    private $snoozed_until;

    /**
     * Warehouse
     * ---
     * Relation : many2one (stock.warehouse)
     * @see \Flux\OdooApiClient\Model\Object\Stock\Warehouse
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var OdooRelation
     */
    private $warehouse_id;

    /**
     * Location
     * ---
     * Relation : many2one (stock.location)
     * @see \Flux\OdooApiClient\Model\Object\Stock\Location
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var OdooRelation
     */
    private $location_id;

    /**
     * Product Template
     * ---
     * Relation : many2one (product.template)
     * @see \Flux\OdooApiClient\Model\Object\Product\Template
     * ---
     * Searchable : yes
     * Sortable : no
     *
     * @var OdooRelation|null
     */
    private $product_tmpl_id;

    /**
     * Product
     * ---
     * Relation : many2one (product.product)
     * @see \Flux\OdooApiClient\Model\Object\Product\Product
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var OdooRelation
     */
    private $product_id;

    /**
     * Product Category
     * ---
     * Select category for the current product
     * ---
     * Relation : many2one (product.category)
     * @see \Flux\OdooApiClient\Model\Object\Product\Category
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var OdooRelation|null
     */
    private $product_category_id;

    /**
     * Unit of Measure
     * ---
     * Default unit of measure used for all stock operations.
     * ---
     * Relation : many2one (uom.uom)
     * @see \Flux\OdooApiClient\Model\Object\Uom\Uom
     * ---
     * Searchable : yes
     * Sortable : no
     *
     * @var OdooRelation|null
     */
    private $product_uom;

    /**
     * Product unit of measure label
     * ---
     * Searchable : no
     * Sortable : no
     *
     * @var string|null
     */
    private $product_uom_name;

    /**
     * Min Quantity
     * ---
     * When the virtual stock equals to or goes below the Min Quantity specified for this field, Odoo generates a
     * procurement to bring the forecasted quantity to the Max Quantity.
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var float
     */
    private $product_min_qty;

    /**
     * Max Quantity
     * ---
     * When the virtual stock goes below the Min Quantity, Odoo generates a procurement to bring the forecasted
     * quantity to the Quantity specified as Max Quantity.
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var float
     */
    private $product_max_qty;

    /**
     * Multiple Quantity
     * ---
     * The procurement quantity will be rounded up to this multiple.  If it is 0, the exact quantity will be used.
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var float
     */
    private $qty_multiple;

    /**
     * Procurement Group
     * ---
     * Moves created through this orderpoint will be put in this procurement group. If none is given, the moves
     * generated by stock rules will be grouped into one big picking.
     * ---
     * Relation : many2one (procurement.group)
     * @see \Flux\OdooApiClient\Model\Object\Procurement\Group
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var OdooRelation|null
     */
    private $group_id;

    /**
     * Company
     * ---
     * Relation : many2one (res.company)
     * @see \Flux\OdooApiClient\Model\Object\Res\Company
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var OdooRelation
     */
    private $company_id;

    /**
     * Allowed Location
     * ---
     * Relation : one2many (stock.location)
     * @see \Flux\OdooApiClient\Model\Object\Stock\Location
     * ---
     * Searchable : no
     * Sortable : no
     *
     * @var OdooRelation[]|null
     */
    private $allowed_location_ids;

    /**
     * Rules used
     * ---
     * Relation : many2many (stock.rule)
     * @see \Flux\OdooApiClient\Model\Object\Stock\Rule
     * ---
     * Searchable : no
     * Sortable : no
     *
     * @var OdooRelation[]|null
     */
    private $rule_ids;

    /**
     * Json Lead Days Popover
     * ---
     * Searchable : no
     * Sortable : no
     *
     * @var string|null
     */
    private $json_lead_days_popover;

    /**
     * Lead Days Date
     * ---
     * Searchable : no
     * Sortable : no
     *
     * @var DateTimeInterface|null
     */
    private $lead_days_date;

    /**
     * Allowed Route
     * ---
     * Relation : many2many (stock.location.route)
     * @see \Flux\OdooApiClient\Model\Object\Stock\Location\Route
     * ---
     * Searchable : no
     * Sortable : no
     *
     * @var OdooRelation[]|null
     */
    private $allowed_route_ids;

    /**
     * Preferred Route
     * ---
     * Relation : many2one (stock.location.route)
     * @see \Flux\OdooApiClient\Model\Object\Stock\Location\Route
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var OdooRelation|null
     */
    private $route_id;

    /**
     * On Hand
     * ---
     * Searchable : no
     * Sortable : no
     *
     * @var float|null
     */
    private $qty_on_hand;

    /**
     * Forecast
     * ---
     * Searchable : no
     * Sortable : no
     *
     * @var float|null
     */
    private $qty_forecast;

    /**
     * To Order
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var float|null
     */
    private $qty_to_order;

    /**
     * Show supplier column
     * ---
     * Searchable : no
     * Sortable : no
     *
     * @var bool|null
     */
    private $show_supplier;

    /**
     * Vendor
     * ---
     * Relation : many2one (product.supplierinfo)
     * @see \Flux\OdooApiClient\Model\Object\Product\Supplierinfo
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var OdooRelation|null
     */
    private $supplier_id;

    /**
     * Created by
     * ---
     * Relation : many2one (res.users)
     * @see \Flux\OdooApiClient\Model\Object\Res\Users
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var OdooRelation|null
     */
    private $create_uid;

    /**
     * Created on
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var DateTimeInterface|null
     */
    private $create_date;

    /**
     * Last Updated by
     * ---
     * Relation : many2one (res.users)
     * @see \Flux\OdooApiClient\Model\Object\Res\Users
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var OdooRelation|null
     */
    private $write_uid;

    /**
     * Last Updated on
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var DateTimeInterface|null
     */
    private $write_date;

    /**
     * @param string $name Name
     *        ---
     *        Searchable : yes
     *        Sortable : yes
     * @param string $trigger Trigger
     *        ---
     *        Selection :
     *            -> auto (Auto)
     *            -> manual (Manual)
     *        ---
     *        Searchable : yes
     *        Sortable : yes
     * @param OdooRelation $warehouse_id Warehouse
     *        ---
     *        Relation : many2one (stock.warehouse)
     *        @see \Flux\OdooApiClient\Model\Object\Stock\Warehouse
     *        ---
     *        Searchable : yes
     *        Sortable : yes
     * @param OdooRelation $location_id Location
     *        ---
     *        Relation : many2one (stock.location)
     *        @see \Flux\OdooApiClient\Model\Object\Stock\Location
     *        ---
     *        Searchable : yes
     *        Sortable : yes
     * @param OdooRelation $product_id Product
     *        ---
     *        Relation : many2one (product.product)
     *        @see \Flux\OdooApiClient\Model\Object\Product\Product
     *        ---
     *        Searchable : yes
     *        Sortable : yes
     * @param float $product_min_qty Min Quantity
     *        ---
     *        When the virtual stock equals to or goes below the Min Quantity specified for this field, Odoo generates a
     *        procurement to bring the forecasted quantity to the Max Quantity.
     *        ---
     *        Searchable : yes
     *        Sortable : yes
     * @param float $product_max_qty Max Quantity
     *        ---
     *        When the virtual stock goes below the Min Quantity, Odoo generates a procurement to bring the forecasted
     *        quantity to the Quantity specified as Max Quantity.
     *        ---
     *        Searchable : yes
     *        Sortable : yes
     * @param float $qty_multiple Multiple Quantity
     *        ---
     *        The procurement quantity will be rounded up to this multiple.  If it is 0, the exact quantity will be used.
     *        ---
     *        Searchable : yes
     *        Sortable : yes
     * @param OdooRelation $company_id Company
     *        ---
     *        Relation : many2one (res.company)
     *        @see \Flux\OdooApiClient\Model\Object\Res\Company
     *        ---
     *        Searchable : yes
     *        Sortable : yes
     */
    public function __construct(
        string $name,
        string $trigger,
        OdooRelation $warehouse_id,
        OdooRelation $location_id,
        OdooRelation $product_id,
        float $product_min_qty,
        float $product_max_qty,
        float $qty_multiple,
        OdooRelation $company_id
    ) {
        $this->name = $name;
        $this->trigger = $trigger;
        $this->warehouse_id = $warehouse_id;
        $this->location_id = $location_id;
        $this->product_id = $product_id;
        $this->product_min_qty = $product_min_qty;
        $this->product_max_qty = $product_max_qty;
        $this->qty_multiple = $qty_multiple;
        $this->company_id = $company_id;
    }

    /**
     * @param DateTimeInterface|null $lead_days_date
     */
    public function setLeadDaysDate(?DateTimeInterface $lead_days_date): void
    {
        $this->lead_days_date = $lead_days_date;
    }

    /**
     * @return OdooRelation|null
     *
     * @SerializedName("route_id")
     */
    public function getRouteId(): ?OdooRelation
    {
        return $this->route_id;
    }

    /**
     * @param OdooRelation $item
     */
    public function removeAllowedRouteIds(OdooRelation $item): void
    {
        if (null === $this->allowed_route_ids) {
            $this->allowed_route_ids = [];
        }

        if ($this->hasAllowedRouteIds($item)) {
            $index = array_search($item, $this->allowed_route_ids);
            unset($this->allowed_route_ids[$index]);
        }
    }

    /**
     * @param OdooRelation $item
     */
    public function addAllowedRouteIds(OdooRelation $item): void
    {
        if ($this->hasAllowedRouteIds($item)) {
            return;
        }

        if (null === $this->allowed_route_ids) {
            $this->allowed_route_ids = [];
        }

        $this->allowed_route_ids[] = $item;
    }

    /**
     * @param OdooRelation $item
     *
     * @return bool
     */
    public function hasAllowedRouteIds(OdooRelation $item): bool
    {
        if (null === $this->allowed_route_ids) {
            return false;
        }

        return in_array($item, $this->allowed_route_ids);
    }

    /**
     * @param OdooRelation[]|null $allowed_route_ids
     */
    public function setAllowedRouteIds(?array $allowed_route_ids): void
    {
        $this->allowed_route_ids = $allowed_route_ids;
    }

    /**
     * @return OdooRelation[]|null
     *
     * @SerializedName("allowed_route_ids")
     */
    public function getAllowedRouteIds(): ?array
    {
        return $this->allowed_route_ids;
    }

    /**
     * @return DateTimeInterface|null
     *
     * @SerializedName("lead_days_date")
     */
    public function getLeadDaysDate(): ?DateTimeInterface
    {
        return $this->lead_days_date;
    }

    /**
     * @return float|null
     *
     * @SerializedName("qty_on_hand")
     */
    public function getQtyOnHand(): ?float
    {
        return $this->qty_on_hand;
    }

    /**
     * @param string|null $json_lead_days_popover
     */
    public function setJsonLeadDaysPopover(?string $json_lead_days_popover): void
    {
        $this->json_lead_days_popover = $json_lead_days_popover;
    }

    /**
     * @return string|null
     *
     * @SerializedName("json_lead_days_popover")
     */
    public function getJsonLeadDaysPopover(): ?string
    {
        return $this->json_lead_days_popover;
    }

    /**
     * @param OdooRelation $item
     */
    public function removeRuleIds(OdooRelation $item): void
    {
        if (null === $this->rule_ids) {
            $this->rule_ids = [];
        }

        if ($this->hasRuleIds($item)) {
            $index = array_search($item, $this->rule_ids);
            unset($this->rule_ids[$index]);
        }
    }

    /**
     * @param OdooRelation $item
     */
    public function addRuleIds(OdooRelation $item): void
    {
        if ($this->hasRuleIds($item)) {
            return;
        }

        if (null === $this->rule_ids) {
            $this->rule_ids = [];
        }

        $this->rule_ids[] = $item;
    }

    /**
     * @param OdooRelation $item
     *
     * @return bool
     */
    public function hasRuleIds(OdooRelation $item): bool
    {
        if (null === $this->rule_ids) {
            return false;
        }

        return in_array($item, $this->rule_ids);
    }

    /**
     * @param OdooRelation[]|null $rule_ids
     */
    public function setRuleIds(?array $rule_ids): void
    {
        $this->rule_ids = $rule_ids;
    }

    /**
     * @param OdooRelation|null $route_id
     */
    public function setRouteId(?OdooRelation $route_id): void
    {
        $this->route_id = $route_id;
    }

    /**
     * @param float|null $qty_on_hand
     */
    public function setQtyOnHand(?float $qty_on_hand): void
    {
        $this->qty_on_hand = $qty_on_hand;
    }

    /**
     * @param OdooRelation $item
     */
    public function removeAllowedLocationIds(OdooRelation $item): void
    {
        if (null === $this->allowed_location_ids) {
            $this->allowed_location_ids = [];
        }

        if ($this->hasAllowedLocationIds($item)) {
            $index = array_search($item, $this->allowed_location_ids);
            unset($this->allowed_location_ids[$index]);
        }
    }

    /**
     * @param OdooRelation|null $create_uid
     */
    public function setCreateUid(?OdooRelation $create_uid): void
    {
        $this->create_uid = $create_uid;
    }

    /**
     * @param DateTimeInterface|null $write_date
     */
    public function setWriteDate(?DateTimeInterface $write_date): void
    {
        $this->write_date = $write_date;
    }

    /**
     * @return DateTimeInterface|null
     *
     * @SerializedName("write_date")
     */
    public function getWriteDate(): ?DateTimeInterface
    {
        return $this->write_date;
    }

    /**
     * @param OdooRelation|null $write_uid
     */
    public function setWriteUid(?OdooRelation $write_uid): void
    {
        $this->write_uid = $write_uid;
    }

    /**
     * @return OdooRelation|null
     *
     * @SerializedName("write_uid")
     */
    public function getWriteUid(): ?OdooRelation
    {
        return $this->write_uid;
    }

    /**
     * @param DateTimeInterface|null $create_date
     */
    public function setCreateDate(?DateTimeInterface $create_date): void
    {
        $this->create_date = $create_date;
    }

    /**
     * @return DateTimeInterface|null
     *
     * @SerializedName("create_date")
     */
    public function getCreateDate(): ?DateTimeInterface
    {
        return $this->create_date;
    }

    /**
     * @return OdooRelation|null
     *
     * @SerializedName("create_uid")
     */
    public function getCreateUid(): ?OdooRelation
    {
        return $this->create_uid;
    }

    /**
     * @return float|null
     *
     * @SerializedName("qty_forecast")
     */
    public function getQtyForecast(): ?float
    {
        return $this->qty_forecast;
    }

    /**
     * @param OdooRelation|null $supplier_id
     */
    public function setSupplierId(?OdooRelation $supplier_id): void
    {
        $this->supplier_id = $supplier_id;
    }

    /**
     * @return OdooRelation|null
     *
     * @SerializedName("supplier_id")
     */
    public function getSupplierId(): ?OdooRelation
    {
        return $this->supplier_id;
    }

    /**
     * @param bool|null $show_supplier
     */
    public function setShowSupplier(?bool $show_supplier): void
    {
        $this->show_supplier = $show_supplier;
    }

    /**
     * @return bool|null
     *
     * @SerializedName("show_supplier")
     */
    public function isShowSupplier(): ?bool
    {
        return $this->show_supplier;
    }

    /**
     * @param float|null $qty_to_order
     */
    public function setQtyToOrder(?float $qty_to_order): void
    {
        $this->qty_to_order = $qty_to_order;
    }

    /**
     * @return float|null
     *
     * @SerializedName("qty_to_order")
     */
    public function getQtyToOrder(): ?float
    {
        return $this->qty_to_order;
    }

    /**
     * @param float|null $qty_forecast
     */
    public function setQtyForecast(?float $qty_forecast): void
    {
        $this->qty_forecast = $qty_forecast;
    }

    /**
     * @return OdooRelation[]|null
     *
     * @SerializedName("rule_ids")
     */
    public function getRuleIds(): ?array
    {
        return $this->rule_ids;
    }

    /**
     * @param OdooRelation $item
     */
    public function addAllowedLocationIds(OdooRelation $item): void
    {
        if ($this->hasAllowedLocationIds($item)) {
            return;
        }

        if (null === $this->allowed_location_ids) {
            $this->allowed_location_ids = [];
        }

        $this->allowed_location_ids[] = $item;
    }

    /**
     * @return string
     *
     * @SerializedName("name")
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @return OdooRelation
     *
     * @SerializedName("warehouse_id")
     */
    public function getWarehouseId(): OdooRelation
    {
        return $this->warehouse_id;
    }

    /**
     * @return OdooRelation
     *
     * @SerializedName("product_id")
     */
    public function getProductId(): OdooRelation
    {
        return $this->product_id;
    }

    /**
     * @param OdooRelation|null $product_tmpl_id
     */
    public function setProductTmplId(?OdooRelation $product_tmpl_id): void
    {
        $this->product_tmpl_id = $product_tmpl_id;
    }

    /**
     * @return OdooRelation|null
     *
     * @SerializedName("product_tmpl_id")
     */
    public function getProductTmplId(): ?OdooRelation
    {
        return $this->product_tmpl_id;
    }

    /**
     * @param OdooRelation $location_id
     */
    public function setLocationId(OdooRelation $location_id): void
    {
        $this->location_id = $location_id;
    }

    /**
     * @return OdooRelation
     *
     * @SerializedName("location_id")
     */
    public function getLocationId(): OdooRelation
    {
        return $this->location_id;
    }

    /**
     * @param OdooRelation $warehouse_id
     */
    public function setWarehouseId(OdooRelation $warehouse_id): void
    {
        $this->warehouse_id = $warehouse_id;
    }

    /**
     * @param DateTimeInterface|null $snoozed_until
     */
    public function setSnoozedUntil(?DateTimeInterface $snoozed_until): void
    {
        $this->snoozed_until = $snoozed_until;
    }

    /**
     * @return OdooRelation|null
     *
     * @SerializedName("product_category_id")
     */
    public function getProductCategoryId(): ?OdooRelation
    {
        return $this->product_category_id;
    }

    /**
     * @return DateTimeInterface|null
     *
     * @SerializedName("snoozed_until")
     */
    public function getSnoozedUntil(): ?DateTimeInterface
    {
        return $this->snoozed_until;
    }

    /**
     * @param bool|null $active
     */
    public function setActive(?bool $active): void
    {
        $this->active = $active;
    }

    /**
     * @return bool|null
     *
     * @SerializedName("active")
     */
    public function isActive(): ?bool
    {
        return $this->active;
    }

    /**
     * @param string $trigger
     */
    public function setTrigger(string $trigger): void
    {
        $this->trigger = $trigger;
    }

    /**
     * @return string
     *
     * @SerializedName("trigger")
     */
    public function getTrigger(): string
    {
        return $this->trigger;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @param OdooRelation $product_id
     */
    public function setProductId(OdooRelation $product_id): void
    {
        $this->product_id = $product_id;
    }

    /**
     * @param OdooRelation|null $product_category_id
     */
    public function setProductCategoryId(?OdooRelation $product_category_id): void
    {
        $this->product_category_id = $product_category_id;
    }

    /**
     * @param OdooRelation $item
     *
     * @return bool
     */
    public function hasAllowedLocationIds(OdooRelation $item): bool
    {
        if (null === $this->allowed_location_ids) {
            return false;
        }

        return in_array($item, $this->allowed_location_ids);
    }

    /**
     * @param float $qty_multiple
     */
    public function setQtyMultiple(float $qty_multiple): void
    {
        $this->qty_multiple = $qty_multiple;
    }

    /**
     * @param OdooRelation[]|null $allowed_location_ids
     */
    public function setAllowedLocationIds(?array $allowed_location_ids): void
    {
        $this->allowed_location_ids = $allowed_location_ids;
    }

    /**
     * @return OdooRelation[]|null
     *
     * @SerializedName("allowed_location_ids")
     */
    public function getAllowedLocationIds(): ?array
    {
        return $this->allowed_location_ids;
    }

    /**
     * @param OdooRelation $company_id
     */
    public function setCompanyId(OdooRelation $company_id): void
    {
        $this->company_id = $company_id;
    }

    /**
     * @return OdooRelation
     *
     * @SerializedName("company_id")
     */
    public function getCompanyId(): OdooRelation
    {
        return $this->company_id;
    }

    /**
     * @param OdooRelation|null $group_id
     */
    public function setGroupId(?OdooRelation $group_id): void
    {
        $this->group_id = $group_id;
    }

    /**
     * @return OdooRelation|null
     *
     * @SerializedName("group_id")
     */
    public function getGroupId(): ?OdooRelation
    {
        return $this->group_id;
    }

    /**
     * @return float
     *
     * @SerializedName("qty_multiple")
     */
    public function getQtyMultiple(): float
    {
        return $this->qty_multiple;
    }

    /**
     * @return OdooRelation|null
     *
     * @SerializedName("product_uom")
     */
    public function getProductUom(): ?OdooRelation
    {
        return $this->product_uom;
    }

    /**
     * @param float $product_max_qty
     */
    public function setProductMaxQty(float $product_max_qty): void
    {
        $this->product_max_qty = $product_max_qty;
    }

    /**
     * @return float
     *
     * @SerializedName("product_max_qty")
     */
    public function getProductMaxQty(): float
    {
        return $this->product_max_qty;
    }

    /**
     * @param float $product_min_qty
     */
    public function setProductMinQty(float $product_min_qty): void
    {
        $this->product_min_qty = $product_min_qty;
    }

    /**
     * @return float
     *
     * @SerializedName("product_min_qty")
     */
    public function getProductMinQty(): float
    {
        return $this->product_min_qty;
    }

    /**
     * @param string|null $product_uom_name
     */
    public function setProductUomName(?string $product_uom_name): void
    {
        $this->product_uom_name = $product_uom_name;
    }

    /**
     * @return string|null
     *
     * @SerializedName("product_uom_name")
     */
    public function getProductUomName(): ?string
    {
        return $this->product_uom_name;
    }

    /**
     * @param OdooRelation|null $product_uom
     */
    public function setProductUom(?OdooRelation $product_uom): void
    {
        $this->product_uom = $product_uom;
    }

    /**
     * @return string
     */
    public static function getOdooModelName(): string
    {
        return 'stock.warehouse.orderpoint';
    }
}
