language: php

php:
    - '7.3'
    - '7.4'

before_script:
    - composer self-update
    - composer install

script:
    - composer validate --strict
    - vendor/bin/ecs check .
    - vendor/bin/phpstan analyse -c phpstan.neon -l max src/
    # Mute since I made an working API Mocker - vendor/bin/phpunit
