<?php

declare(strict_types=1);

namespace Tests\Flux\OdooApiClient\TestModel\Object\Account\Edi;

use DateTimeInterface;
use Flux\OdooApiClient\Model\Object\Base;
use Flux\OdooApiClient\Model\OdooRelation;
use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * Odoo model : account.edi.document
 * ---
 * Name : account.edi.document
 * ---
 * Info :
 * Main super-class for regular database-persisted Odoo models.
 *
 *         Odoo models are created by inheriting from this class::
 *
 *                 class user(Model):
 *                         ...
 *
 *         The system will later instantiate the class once per database (on
 *         which the class' module is installed).
 */
final class Document extends Base
{
    /**
     * Move
     * ---
     * Relation : many2one (account.move)
     * @see \Tests\Flux\OdooApiClient\TestModel\Object\Account\Move
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var OdooRelation
     */
    private $move_id;

    /**
     * Edi Format
     * ---
     * Relation : many2one (account.edi.format)
     * @see \Tests\Flux\OdooApiClient\TestModel\Object\Account\Edi\Format
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var OdooRelation
     */
    private $edi_format_id;

    /**
     * Attachment
     * ---
     * The file generated by edi_format_id when the invoice is posted (and this document is processed).
     * ---
     * Relation : many2one (ir.attachment)
     * @see \Tests\Flux\OdooApiClient\TestModel\Object\Ir\Attachment
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var OdooRelation|null
     */
    private $attachment_id;

    /**
     * State
     * ---
     * Selection :
     *     -> to_send (To Send)
     *     -> sent (Sent)
     *     -> to_cancel (To Cancel)
     *     -> cancelled (Cancelled)
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var string|null
     */
    private $state;

    /**
     * Error
     * ---
     * The text of the last error that happened during Electronic Invoice operation.
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var string|null
     */
    private $error;

    /**
     * Name
     * ---
     * Searchable : yes
     * Sortable : no
     *
     * @var string|null
     */
    private $name;

    /**
     * Format Name
     * ---
     * Searchable : yes
     * Sortable : no
     *
     * @var string|null
     */
    private $edi_format_name;

    /**
     * Created by
     * ---
     * Relation : many2one (res.users)
     * @see \Tests\Flux\OdooApiClient\TestModel\Object\Res\Users
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var OdooRelation|null
     */
    private $create_uid;

    /**
     * Created on
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var DateTimeInterface|null
     */
    private $create_date;

    /**
     * Last Updated by
     * ---
     * Relation : many2one (res.users)
     * @see \Tests\Flux\OdooApiClient\TestModel\Object\Res\Users
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var OdooRelation|null
     */
    private $write_uid;

    /**
     * Last Updated on
     * ---
     * Searchable : yes
     * Sortable : yes
     *
     * @var DateTimeInterface|null
     */
    private $write_date;

    /**
     * @param OdooRelation $move_id Move
     *        ---
     *        Relation : many2one (account.move)
     *        @see \Tests\Flux\OdooApiClient\TestModel\Object\Account\Move
     *        ---
     *        Searchable : yes
     *        Sortable : yes
     * @param OdooRelation $edi_format_id Edi Format
     *        ---
     *        Relation : many2one (account.edi.format)
     *        @see \Tests\Flux\OdooApiClient\TestModel\Object\Account\Edi\Format
     *        ---
     *        Searchable : yes
     *        Sortable : yes
     */
    public function __construct(OdooRelation $move_id, OdooRelation $edi_format_id)
    {
        $this->move_id = $move_id;
        $this->edi_format_id = $edi_format_id;
    }

    /**
     * @return string|null
     *
     * @SerializedName("edi_format_name")
     */
    public function getEdiFormatName(): ?string
    {
        return $this->edi_format_name;
    }

    /**
     * @param DateTimeInterface|null $write_date
     */
    public function setWriteDate(?DateTimeInterface $write_date): void
    {
        $this->write_date = $write_date;
    }

    /**
     * @return DateTimeInterface|null
     *
     * @SerializedName("write_date")
     */
    public function getWriteDate(): ?DateTimeInterface
    {
        return $this->write_date;
    }

    /**
     * @param OdooRelation|null $write_uid
     */
    public function setWriteUid(?OdooRelation $write_uid): void
    {
        $this->write_uid = $write_uid;
    }

    /**
     * @return OdooRelation|null
     *
     * @SerializedName("write_uid")
     */
    public function getWriteUid(): ?OdooRelation
    {
        return $this->write_uid;
    }

    /**
     * @param DateTimeInterface|null $create_date
     */
    public function setCreateDate(?DateTimeInterface $create_date): void
    {
        $this->create_date = $create_date;
    }

    /**
     * @return DateTimeInterface|null
     *
     * @SerializedName("create_date")
     */
    public function getCreateDate(): ?DateTimeInterface
    {
        return $this->create_date;
    }

    /**
     * @param OdooRelation|null $create_uid
     */
    public function setCreateUid(?OdooRelation $create_uid): void
    {
        $this->create_uid = $create_uid;
    }

    /**
     * @return OdooRelation|null
     *
     * @SerializedName("create_uid")
     */
    public function getCreateUid(): ?OdooRelation
    {
        return $this->create_uid;
    }

    /**
     * @param string|null $edi_format_name
     */
    public function setEdiFormatName(?string $edi_format_name): void
    {
        $this->edi_format_name = $edi_format_name;
    }

    /**
     * @param string|null $name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return OdooRelation
     *
     * @SerializedName("move_id")
     */
    public function getMoveId(): OdooRelation
    {
        return $this->move_id;
    }

    /**
     * @return string|null
     *
     * @SerializedName("name")
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string|null $error
     */
    public function setError(?string $error): void
    {
        $this->error = $error;
    }

    /**
     * @return string|null
     *
     * @SerializedName("error")
     */
    public function getError(): ?string
    {
        return $this->error;
    }

    /**
     * @param string|null $state
     */
    public function setState(?string $state): void
    {
        $this->state = $state;
    }

    /**
     * @return string|null
     *
     * @SerializedName("state")
     */
    public function getState(): ?string
    {
        return $this->state;
    }

    /**
     * @param OdooRelation|null $attachment_id
     */
    public function setAttachmentId(?OdooRelation $attachment_id): void
    {
        $this->attachment_id = $attachment_id;
    }

    /**
     * @return OdooRelation|null
     *
     * @SerializedName("attachment_id")
     */
    public function getAttachmentId(): ?OdooRelation
    {
        return $this->attachment_id;
    }

    /**
     * @param OdooRelation $edi_format_id
     */
    public function setEdiFormatId(OdooRelation $edi_format_id): void
    {
        $this->edi_format_id = $edi_format_id;
    }

    /**
     * @return OdooRelation
     *
     * @SerializedName("edi_format_id")
     */
    public function getEdiFormatId(): OdooRelation
    {
        return $this->edi_format_id;
    }

    /**
     * @param OdooRelation $move_id
     */
    public function setMoveId(OdooRelation $move_id): void
    {
        $this->move_id = $move_id;
    }

    /**
     * @return string
     */
    public static function getOdooModelName(): string
    {
        return 'account.edi.document';
    }
}
