<?php

declare(strict_types=1);

namespace Flux\OdooApiClient\Model\Object\BaseImport;

use DateTimeInterface;
use Flux\OdooApiClient\Model\Object\Base;
use Flux\OdooApiClient\Model\Object\Res\Users;

/**
 * Odoo model : base_import.mapping
 * Name : base_import.mapping
 *
 * mapping of previous column:field selections
 *
 * This is useful when repeatedly importing from a third-party
 * system: column names generated by the external system may
 * not match Odoo's field names or labels. This model is used
 * to save the mapping between column names and fields so that
 * next time a user imports from the same third-party systems
 * we can automatically match the columns to the correct field
 * without them having to re-enter the mapping every single
 * time.
 */
final class Mapping extends Base
{
    /**
     * Res Model
     *
     * @var string
     */
    private $res_model;

    /**
     * Column Name
     *
     * @var string
     */
    private $column_name;

    /**
     * Field Name
     *
     * @var string
     */
    private $field_name;

    /**
     * Created by
     *
     * @var Users
     */
    private $create_uid;

    /**
     * Created on
     *
     * @var DateTimeInterface
     */
    private $create_date;

    /**
     * Last Updated by
     *
     * @var Users
     */
    private $write_uid;

    /**
     * Last Updated on
     *
     * @var DateTimeInterface
     */
    private $write_date;

    /**
     * @param string $res_model
     */
    public function setResModel(string $res_model): void
    {
        $this->res_model = $res_model;
    }

    /**
     * @param string $column_name
     */
    public function setColumnName(string $column_name): void
    {
        $this->column_name = $column_name;
    }

    /**
     * @param string $field_name
     */
    public function setFieldName(string $field_name): void
    {
        $this->field_name = $field_name;
    }

    /**
     * @return Users
     */
    public function getCreateUid(): Users
    {
        return $this->create_uid;
    }

    /**
     * @return DateTimeInterface
     */
    public function getCreateDate(): DateTimeInterface
    {
        return $this->create_date;
    }

    /**
     * @return Users
     */
    public function getWriteUid(): Users
    {
        return $this->write_uid;
    }

    /**
     * @return DateTimeInterface
     */
    public function getWriteDate(): DateTimeInterface
    {
        return $this->write_date;
    }
}
