<?php

declare(strict_types=1);

namespace Flux\OdooApiClient\Model\Object\Utm;

use DateTimeInterface;
use Flux\OdooApiClient\Model\Object\Base;
use Flux\OdooApiClient\Model\Object\Res\Company;
use Flux\OdooApiClient\Model\Object\Res\Currency;
use Flux\OdooApiClient\Model\Object\Res\Users;

/**
 * Odoo model : utm.campaign
 * Name : utm.campaign
 *
 * Main super-class for regular database-persisted Odoo models.
 *
 * Odoo models are created by inheriting from this class::
 *
 * class user(Model):
 * ...
 *
 * The system will later instantiate the class once per database (on
 * which the class' module is installed).
 */
final class Campaign extends Base
{
    /**
     * Campaign Name
     *
     * @var null|string
     */
    private $name;

    /**
     * Responsible
     *
     * @var null|Users
     */
    private $user_id;

    /**
     * Stage
     *
     * @var null|Stage
     */
    private $stage_id;

    /**
     * Tags
     *
     * @var Tag
     */
    private $tag_ids;

    /**
     * Is Website
     *
     * @var bool
     */
    private $is_website;

    /**
     * Color Index
     *
     * @var int
     */
    private $color;

    /**
     * Quotation Count
     *
     * @var int
     */
    private $quotation_count;

    /**
     * Revenues generated by the campaign
     *
     * @var int
     */
    private $invoiced_amount;

    /**
     * Company
     *
     * @var Company
     */
    private $company_id;

    /**
     * Currency
     *
     * @var Currency
     */
    private $currency_id;

    /**
     * Created by
     *
     * @var Users
     */
    private $create_uid;

    /**
     * Created on
     *
     * @var DateTimeInterface
     */
    private $create_date;

    /**
     * Last Updated by
     *
     * @var Users
     */
    private $write_uid;

    /**
     * Last Updated on
     *
     * @var DateTimeInterface
     */
    private $write_date;

    /**
     * @param null|string $name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * @param null|Users $user_id
     */
    public function setUserId(Users $user_id): void
    {
        $this->user_id = $user_id;
    }

    /**
     * @param null|Stage $stage_id
     */
    public function setStageId(Stage $stage_id): void
    {
        $this->stage_id = $stage_id;
    }

    /**
     * @param Tag $tag_ids
     */
    public function setTagIds(Tag $tag_ids): void
    {
        $this->tag_ids = $tag_ids;
    }

    /**
     * @param bool $is_website
     */
    public function setIsWebsite(bool $is_website): void
    {
        $this->is_website = $is_website;
    }

    /**
     * @param int $color
     */
    public function setColor(int $color): void
    {
        $this->color = $color;
    }

    /**
     * @return int
     */
    public function getQuotationCount(): int
    {
        return $this->quotation_count;
    }

    /**
     * @return int
     */
    public function getInvoicedAmount(): int
    {
        return $this->invoiced_amount;
    }

    /**
     * @return Company
     */
    public function getCompanyId(): Company
    {
        return $this->company_id;
    }

    /**
     * @return Currency
     */
    public function getCurrencyId(): Currency
    {
        return $this->currency_id;
    }

    /**
     * @return Users
     */
    public function getCreateUid(): Users
    {
        return $this->create_uid;
    }

    /**
     * @return DateTimeInterface
     */
    public function getCreateDate(): DateTimeInterface
    {
        return $this->create_date;
    }

    /**
     * @return Users
     */
    public function getWriteUid(): Users
    {
        return $this->write_uid;
    }

    /**
     * @return DateTimeInterface
     */
    public function getWriteDate(): DateTimeInterface
    {
        return $this->write_date;
    }
}
